### PR TITLE
Correct card text typo

### PR DESCRIPTION
**Pull request by davidopluslau**
This change corrects the black card text, "I drink to forger" -> "I drink to forget".

### CODE REVIEW

**Comment by davidopluslau** [comment]
@KevinBongart long time no see.

**Comment by danielsomekh** [comment]
lgtm, I picked this card so big cudos to me

**Comment by danielsomekh** [comment]
@KevinBongart the game was great! How are you doing?

**Comment by davidopluslau** [comment]
s/cudos/kudos

**Comment by anatg** [comment]
> lgtm, I picked this card so big cudos to me

kudos, not cudos, danny

**Comment by danielsomekh** [comment]
I have no idea what you guys are talking about 🙄

**Comment by danielsomekh** [comment]
s/David Lau/ 👎

**Pull request merged**
